name: Woodside Media
favicon: null
layout_spectrum: 0.1400990376714617
typography_spectrum: 0.02605859888717532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9913893069606274
  lightness: 0.47177178389392793
  saturation: 0.9522944274358451
  rhythmicContrast: 0.24935139040462673
purpose: []
