name: Woodside Media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31821
title: Woodside Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00ffff'
    - '#918ae6'
    - '#e90000'
    - '#3300d2'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
