name: Woodside Media
favicon: null
layout_spectrum: 0.1400990376714617
typography_spectrum: 0.02605859888717532
title: Woodside Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00ffff'
    - '#918ae6'
    - '#e90000'
    - '#3300d2'
  brandStrength: 0.75
  lightness: 0.47177178389392793
  saturation: 0.9522944274358451
  rhythmicContrast: 0.24935139040462673
purpose: []
